---
title: "Beautiful tables with gt()"
author: Andrew Gard
format: html
---

```{r}
#| label: setup
#| include: false

library(gt)
library(tidyverse)
library(modeldata)

# Data preprocessing

scat_table1 <- scat %>% 
  select(Species, 
         Site, 
         Length,
         Diameter,
         Mass,
         d13C,
         d15N) %>% 
  group_by(Species) %>% 
  summarize(across(where(is.numeric), 
                   \(x) round(mean(x, na.rm = TRUE), 1)),
            count = n())

scat_table2 <- scat %>% 
  select(Species, 
         Location,
         Site, 
         Length,
         Diameter,
         Mass,
         d13C,
         d15N) %>% 
  group_by(Species, Site) %>% 
  summarize(across(where(is.numeric), 
                   \(x) round(mean(x, na.rm = TRUE), 1)),
            Count = n())
```

## A great table

```{r}
scat_table1 %>% 
  gt(rowname_col = "Species") %>% 
  cols_label(count ~ "Count") %>% 
  tab_header(title = "California poopies",
             subtitle = "Morphometric data on scat") %>% 
  tab_source_note(md("**Source**: Reid, R. E. B. (2015). A morphometric modeling approach to distinguishing among bobcat, coyote and gray fox scats. *Wildlife Biology*, 21(5), 254-262")) %>% 
  tab_spanner(label = "Physical averages",
              columns = Length:Mass) %>% 
  tab_stubhead(label = "Species")
```

## A stylized version

```{r}
scat_table1 %>% 
  gt() %>% 
  cols_label(count ~ "Count") %>% 
  tab_header(title = "California poopies",
             subtitle = "Morphometric data on scat") %>% 
  tab_source_note(md("**Source**: Reid, R. E. B. (2015). A morphometric modeling approach to distinguishing among bobcat, coyote and gray fox scats. *Wildlife Biology*, 21(5), 254-262")) %>% 
  tab_spanner(label = "Physical averages",
              columns = Length:Mass) %>% 
  opt_stylize(style = 2, color = "blue")
```

# Grouped data

```{r}
scat_table2 %>% 
  ungroup() %>% 
  gt(groupname_col = "Species")
```


